# User data 
kevin = User.create(username: "kevinrocks123", password: 'password')
jill = User.create(username: 'jill789', password: 'jilliscool')

# Starbucks data 
bklyn_location = Starbucks.create(name: "Brooklyn Starbucks")
mhtn_location = Starbucks.create(name: "Manhattan Starbucks")
boston_location = Starbucks.create(name: "Manhattan Starbucks")
la_location = Starbucks.create(name: "Manhattan Starbucks")
london_location = Starbucks.create(name: "Manhattan Starbucks")
texas_location = Starbucks.create(name: "Manhattan Starbucks")
chicago_location = Starbucks.create(name: "Manhattan Starbucks")
rio_location = Starbucks.create(name: "Manhattan Starbucks")
tokyo_location = Starbucks.create(name: "Manhattan Starbucks")
prague_location = Starbucks.create(name: "Manhattan Starbucks")
china_location = Starbucks.create(name: "Manhattan Starbucks")
vienna_location = Starbucks.create(name: "Manhattan Starbucks")
india_location = Starbucks.create(name: "Manhattan Starbucks")
seoul_location = Starbucks.create(name: "Manhattan Starbucks")
phuket_location = Starbucks.create(name: "Manhattan Starbucks")
bali_location = Starbucks.create(name: "Manhattan Starbucks")
hong_kong_location = Starbucks.create(name: "Manhattan Starbucks")
madrid_location = Starbucks.create(name: "Manhattan Starbucks")
venice_location = Starbucks.create(name: "Manhattan Starbucks")
paris_location = Starbucks.create(name: "Manhattan Starbucks")
copenhagen_location = Starbucks.create(name: "Manhattan Starbucks")
