Starbucks.destroy_all
# Starbucks data 
bklyn_location = Starbucks.create(name: "Brooklyn Starbucks")
mhtn_location = Starbucks.create(name: "Manhattan Starbucks")
boston_location = Starbucks.create(name: "Boston Starbucks")
la_location = Starbucks.create(name: "LA Starbucks")
london_location = Starbucks.create(name: "London Starbucks")
texas_location = Starbucks.create(name: "Texas Starbucks")
chicago_location = Starbucks.create(name: "Chicago Starbucks")
rio_location = Starbucks.create(name: "Rio de Janeiro Starbucks")
tokyo_location = Starbucks.create(name: "Tokyo Starbucks")
prague_location = Starbucks.create(name: "Prague Starbucks")
china_location = Starbucks.create(name: "China Starbucks")
vienna_location = Starbucks.create(name: "Vienna Starbucks")
india_location = Starbucks.create(name: "India Starbucks")
seoul_location = Starbucks.create(name: "Seoul Starbucks")
phuket_location = Starbucks.create(name: "Phuket Starbucks")
bali_location = Starbucks.create(name: "Bali Starbucks")
hong_kong_location = Starbucks.create(name: "Hong Kong Starbucks")
madrid_location = Starbucks.create(name: "Madrid Starbucks")
venice_location = Starbucks.create(name: "Venice Starbucks")
paris_location = Starbucks.create(name: "Paris Starbucks")
copenhagen_location = Starbucks.create(name: "Copenhagen Starbucks")

